version: '3.8'
services:
  server:
    build:
      context: ./server

    ports:
      - "4000:4000"
    container_name: server
    volumes:
      - ./server:/app

  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: client
    stdin_open: true
    tty: true
