name: Prettier

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}
      - name: Run Prettier
        uses: actionsx/prettier@v2
        with:
          args: --write '**/*.{css,js,ts,tsx,html,md}'
          prettier_options: --printWidth 120
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Apply prettier changes